Task #16
Vaiki/TMSHW pull request #1
Opened 2022-04-29 12:40 UTC by Vaiki

2022-04-29 13:00 UTC, OKurcheuskaya requested changes

2022-04-29 13:00 UTC, OKurcheuskaya commented on app/src/main/java/com/example/tmshw/RecyclerViewFragment.kt
>      private var binding: FragmentRecyclerViewBinding? = null
use laitenit

2022-04-29 13:00 UTC, OKurcheuskaya commented on app/src/main/java/com/example/tmshw/RecyclerViewFragment.kt
>          inflater: LayoutInflater, container: ViewGroup?,
https://developer.android.com/topic/libraries/view-binding

2022-04-30 06:28 UTC, Vaiki commented on app/src/main/java/com/example/tmshw/RecyclerViewFragment.kt
>      private var binding: FragmentRecyclerViewBinding? = null
https://youtu.be/0nXXUzMyF8c?t=254

2022-04-30 19:03 UTC, Vaiki reviewed
fix

2022-04-30 19:03 UTC, Vaiki commented on app/src/main/java/com/example/tmshw/RecyclerViewFragment.kt
>          inflater: LayoutInflater, container: ViewGroup?,
я использую DataBinding, поэтому так https://developer.android.com/topic/libraries/data-binding/expressions

2022-05-02 08:05 UTC, OKurcheuskaya approved these changes

2022-05-02 08:46 UTC, merged