using mediaPlayer in Service
Vaiki/TMSHW pull request #4
Opened 2022-05-19 12:12 UTC by Vaiki

2022-05-20 09:00 UTC, OKurcheuskaya requested changes
добавь паузу

2022-05-20 09:00 UTC, OKurcheuskaya commented on app/src/main/java/com/example/tmshw/recyclerView/TaskRVAdapter.kt
> +                2 -> {
может тут тоже использовать метод openFragment?

2022-05-20 17:22 UTC, Vaiki commented on app/src/main/java/com/example/tmshw/recyclerView/TaskRVAdapter.kt
> +                2 -> {
Да, русайклер я буду рефакторить

2022-06-06 07:43 UTC, OKurcheuskaya approved these changes

2022-06-10 07:55 UTC, OKurcheuskaya approved these changes

2022-06-12 17:40 UTC, merged